### ISSUE TITLE
Tray Icon not displayed

### ISSUE THREAD

**Issue by psavva** [block-core/blockcore-desktop#26]
Tray Icon not displayed.
![unknown](https://user-images.githubusercontent.com/1454758/151687609-788c69b8-e769-4821-ac80-4db51d70658f.png)

**Comment by psavva** [comment]
This issue is only evident in the packaged version.

**Comment by psavva** [comment]
Resolved by https://github.com/block-core/blockcore-hub/pull/28

**Comment by sondreb** [comment]
Closed by https://github.com/block-core/blockcore-hub/commit/5460035d8831ce82b73dbba19bafc77fbd088383
